-- Voucher diskon dan kolom diskon pada pembayaran/pesanan.
-- Diskonto penjualan dicatat sebagai akun kontra-pendapatan (4-300).

CREATE TABLE public.voucher (
    id bigint NOT NULL,
    kode character varying(50) NOT NULL,
    jenis character varying(20) NOT NULL,
    nilai numeric(19,2) NOT NULL,
    min_belanja numeric(19,2),
    maks_diskon numeric(19,2),
    kuota integer,
    terpakai integer NOT NULL DEFAULT 0,
    aktif boolean NOT NULL DEFAULT true,
    berlaku_dari timestamp(6) without time zone,
    berlaku_sampai timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);

ALTER TABLE public.voucher ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.voucher_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.voucher ADD CONSTRAINT uk_voucher_kode UNIQUE (kode);

ALTER TABLE public.payments ADD COLUMN diskon numeric(19,2) DEFAULT 0;
ALTER TABLE public.payments ADD COLUMN kode_voucher character varying(50);

ALTER TABLE public.pesanan ADD COLUMN diskon numeric(19,2) DEFAULT 0;
ALTER TABLE public.pesanan ADD COLUMN kode_voucher character varying(50);

INSERT INTO akun (kode, nama, tipe, saldo_normal) VALUES
    ('4-300', 'Potongan Penjualan', 'PENDAPATAN', 'DEBIT');
