-- Produk varian: barang yang sama tersedia dalam beberapa pilihan
-- (mis. ukuran cincin, gramasi) dengan harga dan stok masing-masing.
-- Produk tanpa varian tetap memakai harga/stock dasar di tabel produk.

CREATE TABLE public.produk_variant (
    id bigint NOT NULL,
    produk_id bigint NOT NULL,
    nama character varying(100) NOT NULL,
    harga numeric(19,2) NOT NULL,
    harga_modal numeric(19,2) NOT NULL DEFAULT 0,
    stock integer NOT NULL DEFAULT 0,
    aktif boolean NOT NULL DEFAULT true,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);

ALTER TABLE public.produk_variant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produk_variant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.produk_variant
    ADD CONSTRAINT produk_variant_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.produk_variant
    ADD CONSTRAINT fk_produk_variant_produk FOREIGN KEY (produk_id) REFERENCES public.produk(id);

CREATE INDEX idx_produk_variant_produk ON public.produk_variant (produk_id);

-- Keranjang menyimpan pilihan varian. Constraint unik lama (user, produk)
-- diganti dengan (user, produk, varian) lewat ekspresi COALESCE supaya
-- produk tanpa varian (variant_id NULL) tetap hanya muncul satu baris.
ALTER TABLE public.keranjang ADD COLUMN variant_id bigint;

ALTER TABLE ONLY public.keranjang
    DROP CONSTRAINT ukhhgx9oyg9bf61gn8o3j8k3qw8;

CREATE UNIQUE INDEX uk_keranjang_user_produk_variant
    ON public.keranjang (user_id, produk_id, COALESCE(variant_id, 0));

ALTER TABLE ONLY public.keranjang
    ADD CONSTRAINT fk_keranjang_variant FOREIGN KEY (variant_id) REFERENCES public.produk_variant(id);

-- Riwayat pesanan menyimpan salinan nama varian agar tidak berubah
-- bila variannya dihapus atau diganti admin.
ALTER TABLE public.pesanan_item ADD COLUMN variant_id bigint;
ALTER TABLE public.pesanan_item ADD COLUMN nama_variant character varying(100);

ALTER TABLE ONLY public.pesanan_item
    ADD CONSTRAINT fk_pesanan_item_variant FOREIGN KEY (variant_id) REFERENCES public.produk_variant(id);
