-- Pengembalian barang & refund.
-- User mengajukan pengembalian untuk pesanan yang sudah SELESAI, admin
-- menyetujui/menolak, dan stok dikembalikan saat barang benar-benar diterima.

CREATE TABLE public.pengembalian (
    id bigint NOT NULL,
    nomor_pengembalian character varying(50) NOT NULL,
    pesanan_id bigint NOT NULL,
    user_id bigint NOT NULL,
    alasan character varying(1000),
    status character varying(20) NOT NULL DEFAULT 'DIAJUKAN',
    jumlah_refund numeric(19,2) NOT NULL DEFAULT 0,
    catatan_admin character varying(1000),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    approved_at timestamp(6) without time zone,
    diterima_at timestamp(6) without time zone
);

ALTER TABLE public.pengembalian ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pengembalian_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.pengembalian
    ADD CONSTRAINT pengembalian_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.pengembalian
    ADD CONSTRAINT uq_pengembalian_nomor UNIQUE (nomor_pengembalian);

ALTER TABLE ONLY public.pengembalian
    ADD CONSTRAINT fk_pengembalian_pesanan FOREIGN KEY (pesanan_id) REFERENCES public.pesanan(id);

ALTER TABLE ONLY public.pengembalian
    ADD CONSTRAINT fk_pengembalian_user FOREIGN KEY (user_id) REFERENCES public.users(id);

CREATE INDEX idx_pengembalian_pesanan ON public.pengembalian (pesanan_id);
CREATE INDEX idx_pengembalian_user ON public.pengembalian (user_id);
CREATE INDEX idx_pengembalian_status ON public.pengembalian (status);
