-- Tracking resi otomatis.
-- Satu baris per peristiwa perjalanan paket; banyak baris per pesanan
-- membentuk timeline. Status pesanan DIKIRIM menandai awal tracking.

CREATE TABLE public.tracking_pengiriman (
    id bigint NOT NULL,
    pesanan_id bigint NOT NULL,
    nomor_resi character varying(100),
    status character varying(30) NOT NULL,
    keterangan character varying(500),
    lokasi character varying(200),
    updated_at timestamp(6) without time zone
);

ALTER TABLE public.tracking_pengiriman ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tracking_pengiriman_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tracking_pengiriman
    ADD CONSTRAINT tracking_pengiriman_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracking_pengiriman
    ADD CONSTRAINT fk_tracking_pesanan FOREIGN KEY (pesanan_id) REFERENCES public.pesanan(id);

CREATE INDEX idx_tracking_pesanan ON public.tracking_pengiriman (pesanan_id);
CREATE INDEX idx_tracking_nomor_resi ON public.tracking_pengiriman (nomor_resi);
