-- Notifikasi restock.
-- User yang mendaftar ("Beri Tahu Saya") akan diberi tahu saat stok produk
-- (atau varian tertentu) kembali tersedia. Daftar dinonaktifkan setelah terkirim.

CREATE TABLE public.restock_notifikasi (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    produk_id bigint NOT NULL,
    variant_id bigint,
    aktif boolean NOT NULL DEFAULT true,
    created_at timestamp(6) without time zone,
    dikirim_at timestamp(6) without time zone
);

ALTER TABLE public.restock_notifikasi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restock_notifikasi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.restock_notifikasi
    ADD CONSTRAINT restock_notifikasi_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.restock_notifikasi
    ADD CONSTRAINT fk_restock_notifikasi_user FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.restock_notifikasi
    ADD CONSTRAINT fk_restock_notifikasi_produk FOREIGN KEY (produk_id) REFERENCES public.produk(id);

ALTER TABLE ONLY public.restock_notifikasi
    ADD CONSTRAINT fk_restock_notifikasi_variant FOREIGN KEY (variant_id) REFERENCES public.produk_variant(id);

CREATE INDEX idx_restock_notifikasi_produk ON public.restock_notifikasi (produk_id);
CREATE INDEX idx_restock_notifikasi_user ON public.restock_notifikasi (user_id);
CREATE UNIQUE INDEX uk_restock_notifikasi_user_produk_variant
    ON public.restock_notifikasi (user_id, produk_id, COALESCE(variant_id, 0));
