-- Poin loyalitas.
-- User mendapat poin dari pembelian yang lunas dan bisa menukarnya menjadi
-- voucher diskon yang terikat pada pemiliknya (voucher.user_id).

CREATE TABLE public.poin_user (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    saldo_poin bigint NOT NULL DEFAULT 0,
    total_diperoleh bigint NOT NULL DEFAULT 0,
    total_dipakai bigint NOT NULL DEFAULT 0,
    updated_at timestamp(6) without time zone
);

ALTER TABLE public.poin_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.poin_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.poin_user
    ADD CONSTRAINT poin_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.poin_user
    ADD CONSTRAINT uq_poin_user_user UNIQUE (user_id);

ALTER TABLE ONLY public.poin_user
    ADD CONSTRAINT fk_poin_user_user FOREIGN KEY (user_id) REFERENCES public.users(id);

CREATE INDEX idx_poin_user_user ON public.poin_user (user_id);

CREATE TABLE public.riwayat_poin (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    pesanan_id bigint,
    voucher_id bigint,
    jumlah bigint NOT NULL,
    keterangan character varying(255),
    created_at timestamp(6) without time zone
);

ALTER TABLE public.riwayat_poin ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.riwayat_poin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.riwayat_poin
    ADD CONSTRAINT riwayat_poin_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.riwayat_poin
    ADD CONSTRAINT fk_riwayat_poin_user FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.riwayat_poin
    ADD CONSTRAINT fk_riwayat_poin_pesanan FOREIGN KEY (pesanan_id) REFERENCES public.pesanan(id);

-- V14 tidak mendefinisikan primary key pada voucher; ditambahkan di sini
-- karena riwayat_poin.voucher_id mereferensikan voucher.id.
ALTER TABLE ONLY public.voucher ADD CONSTRAINT voucher_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.riwayat_poin
    ADD CONSTRAINT fk_riwayat_poin_voucher FOREIGN KEY (voucher_id) REFERENCES public.voucher(id);

CREATE INDEX idx_riwayat_poin_user ON public.riwayat_poin (user_id);

-- Voucher hasil tukar poin terikat pada user pemiliknya (nullable = voucher umum).
ALTER TABLE public.voucher ADD COLUMN user_id bigint;

ALTER TABLE ONLY public.voucher
    ADD CONSTRAINT fk_voucher_user FOREIGN KEY (user_id) REFERENCES public.users(id);

CREATE INDEX idx_voucher_user ON public.voucher (user_id);
