-- Baseline skema database (dibuat dari struktur yang sudah berjalan).
-- Migrasi ini HANYA dijalankan pada database kosong. Database yang sudah
-- berisi data ditandai baseline oleh Flyway sehingga file ini dilewati.


CREATE TABLE public.alamat (
    id bigint NOT NULL,
    alamat_lengkap text NOT NULL,
    catatan character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    is_default boolean NOT NULL,
    kecamatan character varying(255),
    kelurahan character varying(255),
    kode_pos character varying(255) NOT NULL,
    kota character varying(255),
    nama_lengkap character varying(255) NOT NULL,
    nomor_telepon character varying(255) NOT NULL,
    provinsi character varying(255),
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);

ALTER TABLE public.alamat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alamat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.app_settings (
    id bigint NOT NULL,
    setting_key character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone,
    setting_value text
);

ALTER TABLE public.app_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.chat_messages (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_read boolean NOT NULL,
    message text NOT NULL,
    receiver_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    sender_role character varying(20) NOT NULL,
    CONSTRAINT chat_messages_sender_role_check CHECK (((sender_role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying])::text[])))
);

ALTER TABLE public.chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.keranjang (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    quantity integer NOT NULL,
    updated_at timestamp(6) without time zone,
    produk_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.keranjang ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.keranjang_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.login_otp (
    id bigint NOT NULL,
    expired_at timestamp(6) without time zone,
    otp character varying(255),
    used boolean,
    user_id bigint
);

ALTER TABLE public.login_otp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.login_otp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.notification (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    message character varying(1000) NOT NULL,
    payment_id bigint,
    produk_id bigint,
    is_read boolean,
    read_at timestamp(6) without time zone,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint
);

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.ongkir (
    id bigint NOT NULL,
    estimasi_hari integer,
    provinsi character varying(100) NOT NULL,
    tarif double precision NOT NULL
);

ALTER TABLE public.ongkir ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ongkir_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.payments (
    id bigint NOT NULL,
    amount double precision NOT NULL,
    catatan character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    customer_email character varying(255) NOT NULL,
    customer_name character varying(255) NOT NULL,
    customer_phone character varying(255),
    description character varying(255),
    expired_at timestamp(6) without time zone NOT NULL,
    external_id character varying(255) NOT NULL,
    invoice_url character varying(255) NOT NULL,
    paid_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    xendit_invoice_id character varying(255) NOT NULL,
    alamat_id bigint,
    user_id bigint,
    ongkir double precision
);

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.pesanan (
    id bigint NOT NULL,
    catatan character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    dikemas_at timestamp(6) without time zone,
    dikirim_at timestamp(6) without time zone,
    nomor_pesanan character varying(255) NOT NULL,
    nomor_resi character varying(255),
    selesai_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    total_harga double precision NOT NULL,
    updated_at timestamp(6) without time zone,
    alamat_id bigint,
    payment_id bigint NOT NULL,
    user_id bigint NOT NULL,
    ongkir double precision,
    snapshot_alamat_lengkap text,
    snapshot_kecamatan character varying(255),
    snapshot_kelurahan character varying(255),
    snapshot_kode_pos character varying(255),
    snapshot_kota character varying(255),
    snapshot_nama_lengkap character varying(255),
    snapshot_nomor_telepon character varying(255),
    snapshot_provinsi character varying(255),
    CONSTRAINT pesanan_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'DIKEMAS'::character varying, 'DIKIRIM'::character varying, 'SELESAI'::character varying, 'DIBATALKAN'::character varying])::text[])))
);

ALTER TABLE public.pesanan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pesanan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.pesanan_item (
    id bigint NOT NULL,
    harga_satuan double precision NOT NULL,
    karat_emas integer,
    quantity integer NOT NULL,
    subtotal double precision NOT NULL,
    pesanan_id bigint NOT NULL,
    produk_id bigint NOT NULL,
    gambar_produk text,
    nama_produk character varying(255)
);

ALTER TABLE public.pesanan_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pesanan_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.produk (
    id bigint NOT NULL,
    berat_gram double precision NOT NULL,
    created_at timestamp(6) without time zone,
    gambar text,
    harga double precision NOT NULL,
    karat_emas integer NOT NULL,
    nama character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    stock integer NOT NULL,
    updated_at timestamp(6) without time zone,
    kategori character varying(50),
    deleted_at timestamp(6) without time zone,
    deleted boolean DEFAULT false NOT NULL,
    CONSTRAINT produk_status_check CHECK (((status)::text = ANY ((ARRAY['TERSEDIA'::character varying, 'TIDAK_TERSEDIA'::character varying, 'HABIS'::character varying])::text[])))
);

ALTER TABLE public.produk ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.produk_terjual (
    id bigint NOT NULL,
    harga_saat_beli double precision NOT NULL,
    is_success boolean NOT NULL,
    qty integer NOT NULL,
    tanggal_beli timestamp(6) without time zone NOT NULL,
    total double precision NOT NULL,
    pesanan_id bigint,
    produk_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.produk_terjual ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produk_terjual_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.review (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    komentar text NOT NULL,
    rating integer NOT NULL,
    updated_at timestamp(6) without time zone,
    pesanan_id bigint NOT NULL,
    produk_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.terjual_produk (
    id bigint NOT NULL,
    terjual integer NOT NULL,
    produk_id bigint NOT NULL
);

ALTER TABLE public.terjual_produk ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.terjual_produk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255),
    last_login timestamp(6) without time zone,
    nama_lengkap character varying(255),
    no_hp character varying(255),
    password character varying(255),
    role character varying(255),
    terferifikasi boolean,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying])::text[])))
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.wishlist (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    produk_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.wishlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wishlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.alamat
    ADD CONSTRAINT alamat_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.app_settings
    ADD CONSTRAINT app_settings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.keranjang
    ADD CONSTRAINT keranjang_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.login_otp
    ADD CONSTRAINT login_otp_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ongkir
    ADD CONSTRAINT ongkir_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.pesanan_item
    ADD CONSTRAINT pesanan_item_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.pesanan
    ADD CONSTRAINT pesanan_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.produk
    ADD CONSTRAINT produk_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.produk_terjual
    ADD CONSTRAINT produk_terjual_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.terjual_produk
    ADD CONSTRAINT terjual_produk_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ongkir
    ADD CONSTRAINT uk22vnop27vdmxskuwc2lxum7np UNIQUE (provinsi);

ALTER TABLE ONLY public.app_settings
    ADD CONSTRAINT uk7p82g7l6uve2vd8l30djhxpel UNIQUE (setting_key);

ALTER TABLE ONLY public.terjual_produk
    ADD CONSTRAINT uk8p8r53lmojukyqsf1ed8d4bj UNIQUE (produk_id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT ukbueivmvhh14ov2x0mtej2hfen UNIQUE (external_id);

ALTER TABLE ONLY public.pesanan
    ADD CONSTRAINT ukep81ip5sp0u2pek6wi35wpqkf UNIQUE (payment_id);

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT ukg41d9mqn5nq1puxbln112alk8 UNIQUE (user_id, produk_id);

ALTER TABLE ONLY public.keranjang
    ADD CONSTRAINT ukhhgx9oyg9bf61gn8o3j8k3qw8 UNIQUE (user_id, produk_id);

ALTER TABLE ONLY public.pesanan
    ADD CONSTRAINT ukmtqgksk52que18n4w7tonegf UNIQUE (nomor_pesanan);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT wishlist_pkey PRIMARY KEY (id);

CREATE INDEX idx_chat_created_at ON public.chat_messages USING btree (created_at);

CREATE INDEX idx_chat_receiver_read ON public.chat_messages USING btree (receiver_id, is_read);

CREATE INDEX idx_chat_sender ON public.chat_messages USING btree (sender_id);

CREATE INDEX idx_payment_status_expired ON public.payments USING btree (status, expired_at);

CREATE INDEX idx_payment_user ON public.payments USING btree (user_id);

CREATE INDEX idx_pesanan_created_at ON public.pesanan USING btree (created_at);

CREATE INDEX idx_pesanan_item_pesanan ON public.pesanan_item USING btree (pesanan_id);

CREATE INDEX idx_pesanan_item_produk ON public.pesanan_item USING btree (produk_id);

CREATE INDEX idx_pesanan_status ON public.pesanan USING btree (status);

CREATE INDEX idx_pesanan_user ON public.pesanan USING btree (user_id);

CREATE INDEX idx_produk_terjual_pesanan ON public.produk_terjual USING btree (pesanan_id);

CREATE INDEX idx_produk_terjual_produk ON public.produk_terjual USING btree (produk_id);

CREATE INDEX idx_produk_terjual_tanggal ON public.produk_terjual USING btree (tanggal_beli);

CREATE INDEX idx_review_produk ON public.review USING btree (produk_id);

CREATE INDEX idx_review_user ON public.review USING btree (user_id);

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fk15apk8u3xdxief4avumisx4jq FOREIGN KEY (pesanan_id) REFERENCES public.pesanan(id);

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fk1j39fccsatrcr26i9dly5cqtn FOREIGN KEY (produk_id) REFERENCES public.produk(id);

ALTER TABLE ONLY public.produk_terjual
    ADD CONSTRAINT fk41cp2soasuxtwjcvnh03e253f FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fk6cpw2nlklblpvc7hyt7ko6v3e FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk6ro04n79ii0x48qasban9xm8t FOREIGN KEY (alamat_id) REFERENCES public.alamat(id);

ALTER TABLE ONLY public.produk_terjual
    ADD CONSTRAINT fk74pg6hjhxp36iaie4hu349r2s FOREIGN KEY (produk_id) REFERENCES public.produk(id);

ALTER TABLE ONLY public.pesanan_item
    ADD CONSTRAINT fk89gt0m5u33xa998pd3x61adru FOREIGN KEY (pesanan_id) REFERENCES public.pesanan(id);

ALTER TABLE ONLY public.pesanan
    ADD CONSTRAINT fkafv2e1k638r1ceaxegyok71g FOREIGN KEY (payment_id) REFERENCES public.payments(id);

ALTER TABLE ONLY public.pesanan
    ADD CONSTRAINT fkckvmh7yp6ygwfnpx6qjil89bq FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.produk_terjual
    ADD CONSTRAINT fkcvl3hxklruug0x082m0ccn90j FOREIGN KEY (pesanan_id) REFERENCES public.pesanan(id);

ALTER TABLE ONLY public.keranjang
    ADD CONSTRAINT fkd7wtrxwtcdrrws1tccgwp4qtw FOREIGN KEY (produk_id) REFERENCES public.produk(id);

ALTER TABLE ONLY public.login_otp
    ADD CONSTRAINT fkfcjxqpq6lmmy5h6ah8drjhdl1 FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.terjual_produk
    ADD CONSTRAINT fkgphrff8x8wptkmui195x9wf FOREIGN KEY (produk_id) REFERENCES public.produk(id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkj94hgy9v5fw1munb90tar2eje FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.pesanan
    ADD CONSTRAINT fkklca3lqu1p7dw7ff3xw40vm4e FOREIGN KEY (alamat_id) REFERENCES public.alamat(id);

ALTER TABLE ONLY public.keranjang
    ADD CONSTRAINT fknglis51fhxnredmbnsfdlsedd FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.pesanan_item
    ADD CONSTRAINT fkpx0txeo69tt0fuvvxggk6x6pp FOREIGN KEY (produk_id) REFERENCES public.produk(id);

ALTER TABLE ONLY public.alamat
    ADD CONSTRAINT fkrjbkgdinnnw8yohwsrbybc6qb FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT fksjfbmxlwcbli91yr0ciehijh5 FOREIGN KEY (produk_id) REFERENCES public.produk(id);

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT fktrd6335blsefl2gxpb8lr0gr7 FOREIGN KEY (user_id) REFERENCES public.users(id);

