-- Galeri foto produk: satu produk boleh punya beberapa gambar.
-- Kolom produk.gambar tetap dipakai sebagai foto utama (item pertama).

CREATE TABLE public.produk_gambar (
    id bigint NOT NULL,
    produk_id bigint NOT NULL,
    url text NOT NULL,
    urutan integer NOT NULL DEFAULT 0
);

ALTER TABLE public.produk_gambar ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.produk_gambar_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.produk_gambar
    ADD CONSTRAINT produk_gambar_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.produk_gambar
    ADD CONSTRAINT fk_produk_gambar_produk FOREIGN KEY (produk_id) REFERENCES public.produk(id);

CREATE INDEX idx_produk_gambar_produk ON public.produk_gambar (produk_id, urutan);

INSERT INTO public.produk_gambar (produk_id, url, urutan)
SELECT id, gambar, 0
FROM public.produk
WHERE gambar IS NOT NULL AND btrim(gambar) <> '';
